### ISSUE TITLE
Maps are serialized as fns

### ISSUE THREAD

**Issue by vlaaad** [clojure/data.alpha.replicant-server#1]
When using remote morse and evaluating `{}`, I receive back a r/fn instead of a r/map, e.g. `#r/fn {:id #uuid "b46e78e5-039b-44c7-935f-3cbc4b1ab193"}`. This makes it impossible to inspect maps — they don't even have toStrings:
![image](https://user-images.githubusercontent.com/732554/235356184-dd2b76c0-32ad-4f13-b377-a07ac2958f73.png)

Note: I use a fork of morse that fixes this issue — https://github.com/nubank/morse/issues/2 — by replacing `(first (read+string ...))` with `(read-string ...)` in :valf.

**Comment by fogus** [comment]
@vlaaad Looks like we need some disambiguation in the remotification process. What JVM + Clojure versions are you using?

**Comment by vlaaad** [comment]
Clojure: 
```
{:major 1, :minor 11, :incremental 1, :qualifier nil}
```
Java:
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```
os is windows 11 if that matters.

**Comment by fogus** [comment]
Interestingly, maps dispatching as fns is not easily reproducible. Inside of my dev env they always dispatch as maps and it's not until I run as you did with certain versions of the JDK do I see the same behavior. I committed a temporary fix to main and if you have a few spare cycles then you can try it by cloning the repo and running:

    clj -X:server :host '"localhost"' :port 7272

**Comment by vlaaad** [comment]
I confirm that `main` serializes maps as remote maps now, thanks!
